// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujkSLKQVrwCX54GC7kShtg
// Component: OImqvU5W7f1u
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: ujkSLKQVrwCX54GC7kShtg/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: OImqvU5W7f1u/css
import Ellipse1Icon from "./icons/PlasmicIcon__Ellipse1"; // plasmic-import: CBKJqKeqarlT/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div
              data-plasmic-name={"figmaPaste"}
              data-plasmic-override={overrides.figmaPaste}
              className={classNames(projectcss.all, sty.figmaPaste)}
            >
              <div
                data-plasmic-name={"home"}
                data-plasmic-override={overrides.home}
                className={classNames(projectcss.all, sty.home)}
              >
                <div
                  data-plasmic-name={"jackWardIDulCtMwsOsUnsplash1"}
                  data-plasmic-override={overrides.jackWardIDulCtMwsOsUnsplash1}
                  className={classNames(
                    projectcss.all,
                    sty.jackWardIDulCtMwsOsUnsplash1
                  )}
                />

                <Ellipse1Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"rectangle1"}
                  data-plasmic-override={overrides.rectangle1}
                  className={classNames(projectcss.all, sty.rectangle1)}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__chZ4B)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"55px"}
                  loading={"lazy"}
                  src={{
                    src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NSA2MCI+CiAgPG1hc2sgaWQ9IkxqMmpzMksyWU5RTmEiIGZpbGw9IiNmZmYiPgogICAgPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik01NSAzMEwyNy41IDAgMCAzMHYzMGgzNVYzNy41YTcuNSA3LjUgMCAwMTE1IDBWNjBoNVYzMHptLTQwIDBhNSA1IDAgMDAtNSA1djEwaDEwVjM1YTUgNSAwIDAwLTUtNXoiLz4KICA8L21hc2s+CiAgPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik01NSAzMEwyNy41IDAgMCAzMHYzMGgzNVYzNy41YTcuNSA3LjUgMCAwMTE1IDBWNjBoNVYzMHptLTQwIDBhNSA1IDAgMDAtNSA1djEwaDEwVjM1YTUgNSAwIDAwLTUtNXoiIGZpbGw9IiNEOUQ5RDkiLz4KICA8cGF0aCBkPSJNMjcuNSAwbC43MzctLjY3Ni0uNzM3LS44MDQtLjczNy44MDRMMjcuNSAwek01NSAzMGgxdi0uMzg5bC0uMjYzLS4yODdMNTUgMzB6TTAgMzBsLS43MzctLjY3Ni0uMjYzLjI4N1YzMGgxem0wIDMwaC0xdjFoMXYtMXptMzUgMHYxaDF2LTFoLTF6bTE1IDBoLTF2MWgxdi0xem01IDB2MWgxdi0xaC0xek0xMCA0NUg5djFoMXYtMXptMTAgMHYxaDF2LTFoLTF6TTI2Ljc2My42NzZsMjcuNSAzMCAxLjQ3NC0xLjM1Mi0yNy41LTMwTDI2Ljc2My42NzZ6bS0yNi4wMjYgMzBsMjcuNS0zMC0xLjQ3NC0xLjM1Mi0yNy41IDMwIDEuNDc0IDEuMzUyek0xIDYwVjMwaC0ydjMwaDJ6bTM0LTFIMHYyaDM1di0yem0tMS0yMS41VjYwaDJWMzcuNWgtMnptOC41LTguNWE4LjUgOC41IDAgMDAtOC41IDguNWgyYTYuNSA2LjUgMCAwMTYuNS02LjV2LTJ6bTguNSA4LjVhOC41IDguNSAwIDAwLTguNS04LjV2MmE2LjUgNi41IDAgMDE2LjUgNi41aDJ6TTUxIDYwVjM3LjVoLTJWNjBoMnptNC0xaC01djJoNXYtMnptLTEtMjl2MzBoMlYzMGgtMnptLTQzIDVhNCA0IDAgMDE0LTR2LTJhNiA2IDAgMDAtNiA2aDJ6bTAgMTBWMzVIOXYxMGgyem05LTFIMTB2MmgxMHYtMnptLTEtOXYxMGgyVjM1aC0yem0tNC00YTQgNCAwIDAxNCA0aDJhNiA2IDAgMDAtNi02djJ6IiBmaWxsPSIjMDAwIiBtYXNrPSJ1cmwoI0xqMmpzMksyWU5RTmEpIi8+Cjwvc3ZnPgo=",
                    fullWidth: 55,
                    fullHeight: 60,
                    aspectRatio: 0.916667
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__uwXkQ)}
                  displayHeight={"72px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"66.81356048583984px"}
                  loading={"lazy"}
                  src={{
                    src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MiA3NCI+CiAgPHBhdGggZD0iTTM2LjM5IDE1LjU2YzAgNy45MTctNS4wOSAxMy41NTktMTAuNTA5IDEzLjU1OS01LjQxOCAwLTEwLjUwOC01LjY0Mi0xMC41MDgtMTMuNTZTMjAuNDYzIDIgMjUuODggMmM1LjQyIDAgMTAuNTEgNS42NDEgMTAuNTEgMTMuNTZ6IiBzdHJva2U9IiMwMDAiIHN0cm9rZS13aWR0aD0iNCIvPgogIDxwYXRoIGQ9Ik00Ni43NjMgMTUuNTZjMCA3LjkxNy01LjA5IDEzLjU1OS0xMC41MDkgMTMuNTU5LTUuNDE4IDAtMTAuNTA4LTUuNjQyLTEwLjUwOC0xMy41NlMzMC44MzYgMiAzNi4yNTQgMmM1LjQxOSAwIDEwLjUwOSA1LjY0MSAxMC41MDkgMTMuNTZ6IiBzdHJva2U9IiMwMDAiIHN0cm9rZS13aWR0aD0iNCIvPgogIDxwYXRoIGQ9Ik01NS4yMDUgMTUuODY0SDNDMTAuMTM0IDM2LjczOCA5LjcyMSA0OS4wOSAzIDcyaDUyLjIwNWMtMy4xMTMtMjQuMjk2LTQuNjUtMzYuNzE4IDAtNTYuMTM2eiIgZmlsbD0iI0QzQ0U2RSIvPgogIDxwYXRoIGQ9Ik01NS4yMDUgMTUuODY0Yy00LjY1IDE5LjQxOC0zLjExMyAzMS44NCAwIDU2LjEzNmw3LjkxNC0xNi4xN2MtMS41MjctMTIuODktMS4zODItMjAuMjU5IDAtMzMuNTU5bC03LjkxNC02LjQwN3oiIGZpbGw9IiNEM0NFNkUiLz4KICA8cGF0aCBkPSJNNjkuODE0IDU3LjY2MWMtMS4yMTgtMTIuODgtLjc5NS0xOS4zMDQgMC0yOC45ODNsLTYuNjk1LTYuNDA3Yy0xLjM4MiAxMy4zLTEuNTI3IDIwLjY2OCAwIDMzLjU2bDYuNjk1IDEuODN6IiBmaWxsPSIjRDNDRTZFIi8+CiAgPHBhdGggZD0iTTU1LjIwNSA3MmwxNC42MDktMTQuMzM5LTYuNjk1LTEuODNMNTUuMjA1IDcyeiIgZmlsbD0iI0QzQ0U2RSIvPgogIDxwYXRoIGQ9Ik01NS4yMDUgMTUuODY0SDNDMTAuMTM0IDM2LjczOCA5LjcyMSA0OS4wOSAzIDcyaDUyLjIwNW0wLTU2LjEzNmMtNC42NSAxOS40MTgtMy4xMTMgMzEuODQgMCA1Ni4xMzZtMC01Ni4xMzZsNy45MTQgNi40MDdNNTUuMjA1IDcybDE0LjYwOS0xNC4zMzlNNTUuMjA0IDcybDcuOTE1LTE2LjE3bTYuNjk1IDEuODMxYy0xLjIxOC0xMi44OC0uNzk1LTE5LjMwNCAwLTI4Ljk4M2wtNi42OTUtNi40MDdtNi42OTUgMzUuMzlsLTYuNjk1LTEuODNtMC0zMy41NmMtMS4zODIgMTMuMy0xLjUyNyAyMC42NjggMCAzMy41NiIgc3Ryb2tlPSIjMDAwIiBzdHJva2Utd2lkdGg9IjQiLz4KPC9zdmc+Cg==",
                    fullWidth: 66.81356048583984,
                    fullHeight: 72,
                    aspectRatio: 0.972973
                  }}
                />
              </div>
              <div
                data-plasmic-name={"menu"}
                data-plasmic-override={overrides.menu}
                className={classNames(projectcss.all, sty.menu)}
              >
                <div
                  data-plasmic-name={"rectangle6"}
                  data-plasmic-override={overrides.rectangle6}
                  className={classNames(projectcss.all, sty.rectangle6)}
                />

                <div
                  data-plasmic-name={"rectangle7"}
                  data-plasmic-override={overrides.rectangle7}
                  className={classNames(projectcss.all, sty.rectangle7)}
                />
              </div>
              <div
                data-plasmic-name={"order"}
                data-plasmic-override={overrides.order}
                className={classNames(projectcss.all, sty.order)}
              >
                <div
                  data-plasmic-name={"brookeLarkAgD6Obnxf0QUnsplash1"}
                  data-plasmic-override={
                    overrides.brookeLarkAgD6Obnxf0QUnsplash1
                  }
                  className={classNames(
                    projectcss.all,
                    sty.brookeLarkAgD6Obnxf0QUnsplash1
                  )}
                />
              </div>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "figmaPaste",
    "home",
    "jackWardIDulCtMwsOsUnsplash1",
    "svg",
    "rectangle1",
    "menu",
    "rectangle6",
    "rectangle7",
    "order",
    "brookeLarkAgD6Obnxf0QUnsplash1"
  ],

  section: [
    "section",
    "figmaPaste",
    "home",
    "jackWardIDulCtMwsOsUnsplash1",
    "svg",
    "rectangle1",
    "menu",
    "rectangle6",
    "rectangle7",
    "order",
    "brookeLarkAgD6Obnxf0QUnsplash1"
  ],

  figmaPaste: [
    "figmaPaste",
    "home",
    "jackWardIDulCtMwsOsUnsplash1",
    "svg",
    "rectangle1",
    "menu",
    "rectangle6",
    "rectangle7",
    "order",
    "brookeLarkAgD6Obnxf0QUnsplash1"
  ],

  home: ["home", "jackWardIDulCtMwsOsUnsplash1", "svg", "rectangle1"],
  jackWardIDulCtMwsOsUnsplash1: ["jackWardIDulCtMwsOsUnsplash1"],
  svg: ["svg"],
  rectangle1: ["rectangle1"],
  menu: ["menu", "rectangle6", "rectangle7"],
  rectangle6: ["rectangle6"],
  rectangle7: ["rectangle7"],
  order: ["order", "brookeLarkAgD6Obnxf0QUnsplash1"],
  brookeLarkAgD6Obnxf0QUnsplash1: ["brookeLarkAgD6Obnxf0QUnsplash1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    figmaPaste: makeNodeComponent("figmaPaste"),
    home: makeNodeComponent("home"),
    jackWardIDulCtMwsOsUnsplash1: makeNodeComponent(
      "jackWardIDulCtMwsOsUnsplash1"
    ),
    svg: makeNodeComponent("svg"),
    rectangle1: makeNodeComponent("rectangle1"),
    menu: makeNodeComponent("menu"),
    rectangle6: makeNodeComponent("rectangle6"),
    rectangle7: makeNodeComponent("rectangle7"),
    order: makeNodeComponent("order"),
    brookeLarkAgD6Obnxf0QUnsplash1: makeNodeComponent(
      "brookeLarkAgD6Obnxf0QUnsplash1"
    ),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
